heat_template_version: 2016-10-14

description: >
  Deploy HTTP apache server in cloud.

parameters:
  server_name:
    type: string
    description: Name of the server
  key_name:
    type: string
    description: Name of keypair to assign to server
  image:
    type: string
    description: Name of image to use for server
  flavor:
    type: string
    description: Flavor to use for server
  public_net_id:
    type: string
    description: >
      ID of public network for which floating IP addresses will be allocated
  private_net_id:
    type: string
    description: ID of private network into which server get deployed
  private_subnet_id:
    type: string
    description: ID of private sub network into which server get deployed
  security_group_id:
    type: string
    description: ID of the security group

resources:
  instance_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_param: security_group_id }]

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: instance1_port }
      user_data: |
            #!/bin/sh
            sudo yum install httpd -y
            sudo systemctl restart httpd

            for i in 443 80
              do
                sudo iptables -I INPUT 1 -p tcp -m tcp --dport $i -j ACCEPT -m comment --comment "by murano, Apache server access on HTTPS port $i"
            done
      user_data_format: RAW

  server2_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: instance_port }

outputs:
  instance_private_ip:
    description: IP address of instance in network
    value: { get_attr: [ instance, first_address ] }
