---

parted_optimization: optimal
create_label: true
label: gpt
vg_name: "datavg"

hdds: []
#- /dev/vdc
mounts: []
#- /mnt/
partitions:
- {'partition_type': 'primary', 'start_point': '0%', 'end_point': '100%'}
