---

- name: "Adding MongoDB Repo"
  yum_repository:
    name: "{{ mongodb_repo_info.name }}"
    description: "{{ mongodb_repo_info.description }}"
    baseurl: "{{ mongodb_repo_info.baseurl }}"
    gpgcheck: "{{ mongodb_repo_info.gpgcheck }}"
    enabled: "{{ mongodb_repo_info.enabled }}"
    gpgkey: "{{ mongodb_repo_info.gpgkey }}"
    state: "present"

- name: "Installing MongoDB"
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
  - python-pip
  - mongodb-enterprise

- name: "Ensuring MongoDB Is Enabled and Started"
  service:
    name: "mongod"
    state: "started"
    enabled: yes

- name: "Installing Python Modules"
  pip:
    name: "pymongo"
    state: "present"

- name: "Configuring MongoDB"
  template:
    src: "etc/mongod.conf.j2"
    dest: "{{ mongodb_config }}"
    mode: 0640
    owner: mongod
    group: mongod
  notify: "Restart MongoDB"

- name: "Wait connection to mongo port"
  wait_for:
    host: "{{ ansible_eth1.ipv4.address }}"
    port: 27017
    state: "started"
    delay: 5
  when: inventory_hostname == mongodb_replication_master

- name: "Create admin mongodb user and users"
  include: users.yml
  when: mongodb_create_users

- include: replication.yml
  when: mongodb_replication
