heat_template_version: 2013-05-23

description: >
  Deploy 1 server into an existing neutron tenant network and
  connect to public network.

parameters:
  name:
    type: string
    description: Name of the server
  key_name:
    type: string
    description: Name of keypair to assign to server
  image:
    type: string
    description: Name of image to use for server
  flavor:
    type: string
    description: Flavor to use for server
  public_net_id:
    type: string
    description: >
      ID of public network for which floating IP addresses will be allocated
  private_net_id:
    type: string
    description: ID of private network into which server get deployed
  private_subnet_id:
    type: string
    description: ID of private sub network into which server get deployed
  security_group_id:
    type: string
    description: ID of the security group

resources:
  instance_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_param: security_group_id }]

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: name}
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: instance1_port }
        
outputs:
  instance_private_ip:
    description: IP address of instance in network
    value: { get_attr: [ instance, first_address ] }
