---

- name: "Install parted tools"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - parted

- name: "Create the label on disks"
  shell: parted -s "{{ item }}" mklabel "{{ label }}"
  with_items:
  - "{{ hdds }}"
  when:
  - create_label
  - "{{ item|basename in hostvars[inventory_hostname]['ansible_devices'] }}"

- name: "Create the partitions"
  shell: parted -a "{{ parted_optimization }}" -s "{{ item.0 }}" mkpart "{{ item.1['partition_type'] }}" "{{ item.1['start_point'] }}" "{{ item.1['end_point'] }}"
  with_nested:
  - "{{ hdds }}"
  - "{{ partitions }}"
  when:
  - "{{ item.0|basename in hostvars[inventory_hostname]['ansible_devices'] }}"

- name: "Create the filesystems"
  filesystem:
    dev: "{{ item }}1"
    fstype: xfs
  with_items: "{{ hdds }}"
  when:
  - "{{ item|basename in hostvars[inventory_hostname]['ansible_devices'] }}"

- name: "Mount filesystems to mounts list"
  mount:
    path: "{{ item.1 }}"
    src: "{{ item.0 }}"
    fstype: xfs
    state: present
  with_items:
  - "{{ hdds }}"
  - "{{ mounts }}"
  when:
  - "{{ item.0|basename in hostvars[inventory_hostname]['ansible_devices'] }}"
